### PR TITLE
Fix #440 Webview loading without delegate (option 2)

### LINKED ISSUE #440: Custom delegate on WKWebView is replaced by mock when snapshotting
When a user sets a custom navigation delegate on a WKWebView and makes a snapshot of a view containing this web view, the navigation delegate [may be replaced](https://github.com/pointfreeco/swift-snapshot-testing/blob/main/Sources/SnapshotTesting/Common/View.swift#L631) by a stub that makes sure the snapshotting lib knows when to snapshot the web view. This works great when users don't implement a custom WKNavigationDelegate themselves. But when a user implements a custom delegate themselves this fails. 

Consider for example a custom delegate that limits the web view to github.com and opens the browser as soon as the user taps on a link outside of github.com

```
class GithubNavigationDelegate: NSObject, WKNavigationDelegate {
  override init() { }

  public func webView(
    _ webView: WKWebView,
    decidePolicyFor navigationAction: WKNavigationAction,
    decisionHandler: @escaping (WKNavigationActionPolicy) -> Void
  ) {
    // limit to webpages on to github.com
    guard navigationAction.request.url?.host == "github.com" else {
      decisionHandler(.cancel)
      // Warn user and open url in browser instead
      return
    }

    decisionHandler(.allow)
  }
}


webview.navigationDelegate = GithubNavigationDelegate()
```

This can't be snapshot tested at the moment because the delegate is removed as soon as a snapshot is made. 

I think this could be fixed by retaining the original delegate, implementing all the possible delegate methods and forwarding all the calls to the original delegate. I'll see if I can draft up a PR. Please let me know if you think of another way of dealing with this issue. 

Finally, many thanks for all the work on this great lib 👏🏼  so far, hopefully I can contribute back a bit.

### PR DESCRIPTION
**Pull request by teameh**
While testing https://github.com/pointfreeco/swift-snapshot-testing/pull/442 another time I suddenly thought it might also be possible to remove the delegate altogether and just observe the `isLoading` property on the WKWebView. 

I've implemented that in this PR. Happy to hear your thoughts. See comments below.

### CODE REVIEW

File: Tests/SnapshotTestingTests/SnapshotTestingTests.swift [hunk 1]
```diff
@@ -1024,6 +1024,80 @@ final class SnapshotTestingTests: XCTestCase {
...
+    _ = manipulatingWKWebViewNavigationDelegate
+  }
+
+  #if os(iOS) || os(macOS)
+  func testWebViewWithRealUrl() throws {
+    let manipulatingWKWebViewNavigationDelegate = ManipulatingWKWebViewNavigationDelegate()
+    let webView = WKWebView()
+    webView.navigationDelegate = manipulatingWKWebViewNavigationDelegate
+
+    webView.load(URLRequest(url: URL(string: "https://www.pointfree.co")!))
```
Comment (teameh) [inline Tests/SnapshotTestingTests/SnapshotTestingTests.swift:1059]: This loads an actual URL. Is that something you want to prevent in the unit tests? I can image you want to avoid it, but it's the best real life example..

**Review by stephencelis — APPROVED** [review]
Great solution!

**Comment by teameh** [comment]
Thanks @stephencelis !

**Comment by teameh** [comment]
@stephencelis any idea when you're going to branch off the next release?

**Comment by teameh** [comment]
@stephencelis? It would be great if we could use this in production

**Comment by teameh** [comment]
This is part of 1.9.0 as well right? Don't see it in the release notes 🤓

**Comment by teameh** [comment]
This is part of 1.9.0 as well right @stephencelis? I don't see it in the release notes 🤓

**Comment by teameh** [comment]
\0/ thanks for merging 👯 😃
